import { useSEO } from "@/hooks/use-seo";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

export default function Disclaimer() {
  useSEO({ title: "Disclaimer | ImageToText.fun", description: "Important limitations regarding OCR accuracy and usage." });

  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <h1 className="text-4xl font-extrabold tracking-tight mb-8">Disclaimer</h1>
          <div className="prose prose-lg dark:prose-invert max-w-none text-muted-foreground">
            
            <h2 className="text-foreground mt-8">Accuracy Limitations</h2>
            <p>
              While ImageToText.fun utilizes advanced, state-of-the-art Optical Character Recognition (OCR) technology, text extraction is an inherently imperfect process. <strong>We do not guarantee 100% accuracy of the extracted text.</strong> 
            </p>
            <p>
              Accuracy can be significantly affected by numerous factors, including but not limited to:
            </p>
            <ul>
              <li>Image resolution and blurriness</li>
              <li>Lighting conditions and contrast</li>
              <li>Unusual, stylized, or highly cursive fonts</li>
              <li>Handwriting legibility</li>
              <li>Damage, stains, or artifacts on the original document</li>
              <li>Complex layouts, multiple columns, or embedded tables</li>
            </ul>

            <h2 className="text-foreground mt-8">Not for Medical or Legal Reliance</h2>
            <p>
              <strong>The text generated by our tool should not be relied upon for critical medical, legal, or financial decisions without thorough human verification.</strong>
            </p>
            <p>
              If you are processing prescriptions, medical records, contracts, legal statutes, or financial statements, you must manually review the extracted text against the original image to ensure absolute fidelity. A single misread character (e.g., a "1" read as a "7", or a missing decimal point) can have severe consequences. We accept no liability for damages or losses incurred due to errors in text extraction.
            </p>

            <h2 className="text-foreground mt-8">Data Privacy</h2>
            <p>
              As outlined in our Privacy Policy, all processing occurs locally on your device. We do not upload or store your documents. Consequently, we cannot help you recover lost text once you clear the tool or refresh the page.
            </p>

          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
